### ISSUE TITLE
Error earthacrosstime

### ISSUE THREAD

**Issue by andresdegante** [doersino/earthacrosstime#8]
Hello, I am very grateful to have aerial, and I wanted to try earthacrosstime, I have configured the ini with the mastodon access token but when I run python3 earthacrosstime.py I get this error:

Traceback (most recent call last):
  File "/home/Selmo/earthacrosstime/earthacrosstime.py", line 1128, in <module>
    main()
  File "/home/Selmo/earthacrosstime/earthacrosstime.py", line 976, in main
    config = ConfigObj(args.config_path, unrepr=True)
  File "/home/Selmo/earthacrosstime/lib/python3.9/site-packages/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/home/Selmo/earthacrosstime/lib/python3.9/site-packages/configobj.py", line 1318, in _load
    raise error
configobj.UnreprError: Parse error from unrepr-ing value at line 159.

**Comment by andresdegante** [comment]
I miss "", thanks
